

spring:
  #datasource
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.100.125:3306/db_mybatis
    driver-class-name: com.mysql.cj.jdbc.Driver
    #切换默认datasource为druid
    type: com.alibaba.druid.pool.DruidDataSource

    # 数据源 druid 其他配置
    #黄色背景（在DataSourceProperties中没有对应的属性，不能注入。需要自己写一个JavaConfig）
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #  配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

#配置MyBatis
mybatis:
  #指定全局配置文件的位置
  config-location:classpath: mybatis/mybatis-config.xml
  #指定sql映射文件的位置
  mapper-locations: classpath:mybatis/mapper/*.xml


#    schema:
#      - classpath:sql/department.sql
#      - classpath:sql/employee.sql
#    #在SpringBoot2.x中,我们需要在配置文件中配置一下

#    initialization-mode: always